### ISSUE TITLE
RPCCLIENT_TIMEOUT customizable

### ISSUE THREAD

**Issue by reddec** [toorop/go-bitcoind#3]
Good day!
Is it possible to expose somewhere request timeouts? Maybe in `NewWithTimeout(...)`
According to comments, `RPCCLIENT_TIMEOUT` was planned as default value, but now no way to override it....

**Comment by toorop** [comment]
You can override it, you just have to edit:
https://github.com/toorop/go-bitcoind/blob/ce9970d969c2982a840e4b7024f5f7f33f578b62/bitcoind.go#L15

But you are right it will be much easier if we do not have to edit source code., i'll do it... if i can find time to.

**Comment by shade** [comment]
Should be closed, as per #10
