### ISSUE TITLE
getinfo deprecated

### ISSUE THREAD

**Issue by frranck** [toorop/go-bitcoind#5]
Hello Stéphane,

Since bitcoind 0.16.0 the  RPC getinfo was removed. 

ref:
https://github.com/bitcoin/bitcoin/blob/d3f4dd313e5fe58903caf2f4d04827e7f7944e17/doc/release-notes/release-notes-0.16.0.md#low-level-changes

Any plan to update your library ? 
Where did you get the json definition of the rpc calls ? Can't find the documentation.

Regards
Franck

**Comment by toorop** [comment]
Franck,

I'm currently on holiday 😎, I'll check that when I get back at the end of the month.
For the documentation look https://bitcoin.org/en/developer-reference

**Comment by kaythxbye** [comment]
Is there any update on this topic?

**Comment by toorop** [comment]
i do not have time for now, feel free to do a PR if you want.
